pipelines:
  branches:
    develop:
      - step:
          image: php:7.1.3
          caches: 
            - vendor
            - node
          script:
            # Update and install dependencies
            - apt-get update && apt-get install -y unzip libjpeg62-turbo-dev libpng12-dev libfreetype6-dev
            - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            - docker-php-ext-install -j$(nproc) gd
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            # install laravel dependencies
            - composer install
            # Create .env file
            - echo -e $ENV_FILE > .env
            # Bitbucket saves environment variables as a single line - in my case I can just create a new line on spaces
            - sed -i 's/ /\n/g' .env
            # run the tests
            - vendor/bin/phpunit
          artifacts:
            - vendor/**
            - node_modules/**
            - .env

      - step:
          image: atlassian/default-image:2
          services:
            - docker
          script: 
            - docker login $REGISTRY --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD
            
            - export IMAGE_NAME=$REGISTRY/app:${BITBUCKET_COMMIT:0:8}
            - docker build -t $IMAGE_NAME . -f deploy/app.prod.docker
            - docker push $IMAGE_NAME
            # Create a new step or command that upgrades your running containers
definitions:
  caches:
    vendor: ~/vendor

